{% set name = "dua-cli" %}
{% set version = "2.29.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Byron/dua-cli/archive/v{{ version }}.tar.gz
  sha256: 69ae562a340b11668d8f43c6cd2de1a0777fa0afb951c6338dc58b62e86bb550

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses

test:
  commands:
    - dua --help

about:
  home: https://lib.rs/crates/dua-cli
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: View disk space usage and delete unwanted data, fast
  dev_url: https://github.com/Byron/dua-cli

extra:
  recipe-maintainers:
    - danielnachun
