context:
  version: "2.31.0"

package:
  name: dua-cli
  version: ${{ version }}

source:
  url: https://github.com/Byron/dua-cli/archive/v${{ version }}.tar.gz
  sha256: e338d61af692898560851894fae4f26ba1435700b8871ee008e6c5b48bd0e34c

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - dua --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: View disk space usage and delete unwanted data, fast
  homepage: https://lib.rs/crates/dua-cli
  repository: https://github.com/Byron/dua-cli

extra:
  recipe-maintainers:
    - danielnachun
