context:
  version: "2.32.2"

package:
  name: dua-cli
  version: ${{ version }}

source:
  url: https://github.com/Byron/dua-cli/archive/v${{ version }}.tar.gz
  sha256: 8a3495d2ec0c9bee961e512c79b11c9945797a3d4f979b4ec63fd50d73d80c94

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - dua --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: View disk space usage and delete unwanted data, fast
  homepage: https://lib.rs/crates/dua-cli
  repository: https://github.com/Byron/dua-cli

extra:
  recipe-maintainers:
    - danielnachun
